algoritmo "Soma entre dois vetores"
// Função :
// Autor :
// Data : 17/10/2023
// Seção de Declarações 
var
   num_vet             : vetor[1..50] de real
   soma                 : inteiro
   cont                 : inteiro
inicio
// Seção de Comandos
//Entrada de Dados
   para cont de 1 ate 2 faca
      escreval("Informe um número: ")
      leia(num_vet[cont])
   fimpara

// Saída de Dados
   escreval("O resultado é: ", num_vet[1] + num_vet[2])
fimalgoritmo
